
const mockData = {
    id: "1",
    name: "Stunt Truck",
    productCode: "60146",
    properties: [
      { key: "Year", value: "2020", icon: "" },
      { key: "Pieces", value: "91", icon: "" },
      { key: "Weigth", value: "12", icon: "" },
      { key: "Category", value: "Pirate", icon: "" }
    ],
    images: [
      {
        src:
          "https://www.lego.com/cdn/cs/set/assets/blt8f957cbc4a955eea/60146.jpg"
      },
      {
        src:
          "https://www.lego.com/cdn/cs/set/assets/blt6432fbc70e26d6cb/60146_alt1.jpg"
      },
      {
        src:
          "https://www.lego.com/cdn/cs/set/assets/blt9a199b7635a691a1/60146_alt2.jpg"
      },
      {
        src:
          "https://www.lego.com/cdn/cs/set/assets/blt3ed5af4fa976d11b/60146_alt3.jpg"
      },
      {
        src:
          "https://www.lego.com/cdn/cs/set/assets/blt42215ab451dd5542/60146_alt4.jpg"
      }
    ],
    bricks: [
        {
            itemNo: 4298609,
            itemDescr: "MINI CRASH HELMET",
            colourLikeDescr: "White",
            colourDescr: "WHITE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4298609",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 5670,
            designId: 30124,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4515359,
            itemDescr: "ROOF TILE 1X4X1",
            colourLikeDescr: "White",
            colourDescr: "WHITE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4515359",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 2220,
            designId: 60477,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 371001,
            itemDescr: "PLATE 1X4",
            colourLikeDescr: "White",
            colourDescr: "WHITE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/371001",
            maxQty: 3,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 19009,
            designId: 3710,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4560178,
            itemDescr: "FLAT TILE 2X4",
            colourLikeDescr: "White",
            colourDescr: "WHITE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4560178",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 10705,
            designId: 87079,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 306901,
            itemDescr: "FLAT TILE 1X2",
            colourLikeDescr: "White",
            colourDescr: "WHITE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/306901",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 31902,
            designId: 3069,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4193068,
            itemDescr: "PLATE 4X4X2/3",
            colourLikeDescr: "White",
            colourDescr: "WHITE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4193068",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 3557,
            designId: 45677,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 6023806,
            itemDescr: "PLATE W. BOW 1X4X2/3",
            colourLikeDescr: "White",
            colourDescr: "WHITE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/6023806",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 7044,
            designId: 93273,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 434921,
            itemDescr: "MEGAPHONE",
            colourLikeDescr: "Red",
            colourDescr: "BR.RED",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/434921",
            maxQty: 8,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 22419,
            designId: 4349,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 302321,
            itemDescr: "PLATE 1X2",
            colourLikeDescr: "Red",
            colourDescr: "BR.RED",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/302321",
            maxQty: 5,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 27045,
            designId: 3023,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 9566,
            itemDescr: "CONSOLE W/ST.WHEEL B/BLA",
            colourLikeDescr: "Blue",
            colourDescr: "BR.BLUE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/9566",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 12097,
            designId: 73081,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 6153335,
            itemDescr: "MINI HEAD  NO. 1966",
            colourLikeDescr: "Yellow",
            colourDescr: "BR.YEL",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/6153335",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 7722,
            designId: 26881,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 6100429,
            itemDescr: "MINI UPPER PART NO. 2874",
            colourLikeDescr: "Black",
            colourDescr: "BLACK",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/6100429",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: -1,
            designId: 76382,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4515368,
            itemDescr: "PLATE 1X2 W/SHAFT Ø3.2",
            colourLikeDescr: "Black",
            colourDescr: "BLACK",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4515368",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 2159,
            designId: 60478,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 241226,
            itemDescr: "RADIATOR GRILLE 1X2",
            colourLikeDescr: "Black",
            colourDescr: "BLACK",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/241226",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 6315,
            designId: 2412,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4541191,
            itemDescr: "ROOF TILE W. LATTICE 1x2x2/3",
            colourLikeDescr: "Black",
            colourDescr: "BLACK",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4541191",
            maxQty: 4,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 18693,
            designId: 61409,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 6118829,
            itemDescr: "ANGLE PLATE 1X2 / 2X4",
            colourLikeDescr: "Black",
            colourDescr: "BLACK",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/6118829",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 8568,
            designId: 21731,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4619323,
            itemDescr: "TYRE NORMAL WIDE Ø30,4 X 14",
            colourLikeDescr: "Black",
            colourDescr: "BLACK",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4619323",
            maxQty: 4,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 1631,
            designId: 92402,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 379526,
            itemDescr: "PLATE 2X6",
            colourLikeDescr: "Black",
            colourDescr: "BLACK",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/379526",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 4574,
            designId: 3795,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 243126,
            itemDescr: "FLAT TILE 1X4",
            colourLikeDescr: "Black",
            colourDescr: "BLACK",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/243126",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 13625,
            designId: 2431,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4504187,
            itemDescr: "Plate 1x2 w. spoiler",
            colourLikeDescr: "Black",
            colourDescr: "BLACK",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4504187",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 8196,
            designId: 50949,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 302126,
            itemDescr: "PLATE 2X3",
            colourLikeDescr: "Black",
            colourDescr: "BLACK",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/302126",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 14489,
            designId: 3021,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 6053077,
            itemDescr: "PLATE W. BOW  2X2X2/3",
            colourLikeDescr: "Black",
            colourDescr: "BLACK",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/6053077",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 10050,
            designId: 15068,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4548180,
            itemDescr: "ROOF TILE 1 X 2 X 2/3, ABS",
            colourLikeDescr: "Black",
            colourDescr: "BLACK",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4548180",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 28965,
            designId: 85984,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 6170597,
            itemDescr: "MUDGUARD 3X4, W/ PLATE, NO. 1",
            colourLikeDescr: "Black",
            colourDescr: "BLACK",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/6170597",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 1116,
            designId: 28326,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 300126,
            itemDescr: "BRICK 2X4",
            colourLikeDescr: "Black",
            colourDescr: "BLACK",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/300126",
            maxQty: 3,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 12849,
            designId: 3001,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4650498,
            itemDescr: "FLAT TILE 1X1, ROUND",
            colourLikeDescr: "White",
            colourDescr: "TR.",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4650498",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 13002,
            designId: 98138,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4646864,
            itemDescr: "FLAT TILE 1X1, ROUND",
            colourLikeDescr: "Red",
            colourDescr: "TR.RED",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4646864",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 16874,
            designId: 98138,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4650500,
            itemDescr: "FLAT TILE 1X1, ROUND",
            colourLikeDescr: "Yellow",
            colourDescr: "TR.YEL",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4650500",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 51619,
            designId: 98138,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 6106027,
            itemDescr: "CORNER PLATE 1X2X2",
            colourLikeDescr: "",
            colourDescr: "BR.ORANGE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/6106027",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 5648,
            designId: 2420,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4120158,
            itemDescr: "MINI LOWER PART",
            colourLikeDescr: "",
            colourDescr: "BR.ORANGE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4120158",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 11745,
            designId: 73200,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 6170595,
            itemDescr: "MUDGUARD 3X4, W/ PLATE, NO. 1",
            colourLikeDescr: "",
            colourDescr: "BR.ORANGE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/6170595",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 0,
            designId: 28326,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 6067913,
            itemDescr: "PLATE W. BOW  2X2X2/3",
            colourLikeDescr: "",
            colourDescr: "BR.ORANGE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/6067913",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 1055,
            designId: 15068,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4159007,
            itemDescr: "PLATE 2X2",
            colourLikeDescr: "",
            colourDescr: "BR.ORANGE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4159007",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 23119,
            designId: 3022,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4118782,
            itemDescr: "PLATE 1X4",
            colourLikeDescr: "",
            colourDescr: "BR.ORANGE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4118782",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 18627,
            designId: 3710,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4121739,
            itemDescr: "BRICK 1X2",
            colourLikeDescr: "",
            colourDescr: "BR.ORANGE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4121739",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 4375,
            designId: 3004,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 6092650,
            itemDescr: "WALL ELEMENT 1X4X1 ABS",
            colourLikeDescr: "",
            colourDescr: "BR.ORANGE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/6092650",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 1015,
            designId: 15207,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4558595,
            itemDescr: "FLAT TILE 1X1",
            colourLikeDescr: "",
            colourDescr: "BR.ORANGE",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4558595",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 49064,
            designId: 3070,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4124083,
            itemDescr: "WINDSCREEN 36 GR. 3X4X1 1/3",
            colourLikeDescr: "",
            colourDescr: "TR.BROWN",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4124083",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 3696,
            designId: 2437,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 6244785,
            itemDescr: "MINI VISOR 2",
            colourLikeDescr: "",
            colourDescr: "TR.BROWN",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/6244785",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 54251,
            designId: 35334,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4598526,
            itemDescr: "PLATE 1X2 W. VERTICAL GRIP",
            colourLikeDescr: "Grey",
            colourDescr: "MED. ST-GREY",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4598526",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 23885,
            designId: 92280,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4211358,
            itemDescr: "ANGLE PLATE 1X2/1X4",
            colourLikeDescr: "Grey",
            colourDescr: "MED. ST-GREY",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4211358",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: -5,
            designId: 2436,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4211395,
            itemDescr: "PLATE 2X4",
            colourLikeDescr: "Grey",
            colourDescr: "MED. ST-GREY",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4211395",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 1574,
            designId: 3020,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 6086709,
            itemDescr: "PLATE 1X4 SPLIT-LEVEL",
            colourLikeDescr: "Grey",
            colourDescr: "DK. ST. GREY",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/6086709",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: -1,
            designId: 18624,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4509884,
            itemDescr: "WHEEL SUSPENSION 2X4 W. SNAP",
            colourLikeDescr: "Grey",
            colourDescr: "DK. ST. GREY",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4509884",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 5452,
            designId: 30157,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4543086,
            itemDescr: "PLATE 1X2 WITH SLIDE",
            colourLikeDescr: "Grey",
            colourDescr: "DK. ST. GREY",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4543086",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 8023,
            designId: 32028,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 4259673,
            itemDescr: "PLATE 4x12 W. BOTTOM 2X4X2/3",
            colourLikeDescr: "Grey",
            colourDescr: "DK. ST. GREY",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/4259673",
            maxQty: 1,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 1256,
            designId: 52036,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 6109685,
            itemDescr: "RIM WIDE 18x14 W. HOLE Ø4.8",
            colourLikeDescr: "",
            colourDescr: "W.GOLD",
            maingroupDescr: "Bricks, Special",
            asset: "https://www.lego.com/service/bricks/5/2/6109685",
            maxQty: 4,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 1137,
            designId: 20896,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        },
        {
            itemNo: 6100030,
            itemDescr: "BEAM 1X1",
            colourLikeDescr: "Grey",
            colourDescr: "DK. ST. GREY",
            maingroupDescr: "Bricks, Special Circles And Angles",
            asset: "https://www.lego.com/service/bricks/5/2/6100030",
            maxQty: 2,
            ip: false,
            price: -1,
            cId: "CAD",
            sQty: 26761,
            designId: 18654,
            priceStr: "",
            priceWithTaxStr: "",
            itemUnavailable: false,
            unavailableLink: null,
            unavailableReason: null
        }
    ]
  };

export function getProduct(productCode) {
    return mockData;
}
